# Generated by Django 3.2.4 on 2021-07-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelters', '0002_owner_shelter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='animal_shelters.animaltype'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='food',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='animal_shelters.food'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
