# Generated by Django 3.2.4 on 2021-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelters', '0004_auto_20210714_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalowner',
            name='end',
            field=models.DateField(null=True),
        ),
    ]
