# Generated by Django 3.2.4 on 2021-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelters', '0013_auto_20210715_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='donations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='regulations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
