# Generated by Django 3.2.4 on 2021-07-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelters', '0014_auto_20210716_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaltype',
            old_name='FCI_number',
            new_name='breed_number',
        ),
    ]
