# Generated by Django 3.2.4 on 2021-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelters', '0015_rename_fci_number_animaltype_breed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ManyToManyField(null=True, through='animal_shelters.AnimalOwner', to='animal_shelters.Owner'),
        ),
    ]
