# Generated by Django 3.2.4 on 2021-07-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelters', '0016_alter_animal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcare',
            name='animal',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal_shelters.animal'),
        ),
    ]
